export const DOCUMENTS_RETREIVED = 'DOCUMENTS_RETREIVED'
export const DOCUMENT_ADDED = 'DOCUMENT_ADDED'
export const DOCUMENT_DELETED = 'DOCUMENT_DELETED'
export const DOCUMENT_FILE_LOADED = "DOCUMENT_FILE_LOADED"
export const DOCUMENT_CONTENT_LOADED = "DOCUMENT_CONTENT_LOADED"
